-- =====================================================================
--  Dental Clinic — مخطط قاعدة بيانات Supabase (Postgres)
--  نفّذ هذا الملف كاملاً في:  Supabase Dashboard > SQL Editor > New query
--  آمن للتشغيل أكثر من مرة (idempotent).
-- =====================================================================

-- ---------------------------------------------------------------------
--  1) الجداول (نسخة مطابقة لجداول SQLite في تطبيق السطح المكتب)
-- ---------------------------------------------------------------------

create table if not exists public.users (
  id            bigint generated by default as identity primary key,
  username      text not null unique,
  password_hash text not null default '',
  role          text not null default 'cashier',
  full_name     text not null default '',
  permissions   text not null default '',
  created_at    text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.patients (
  id                  bigint generated by default as identity primary key,
  name                text not null,
  phone               text not null default '',
  birth_date          text not null default '',
  gender              text not null default '',
  address             text not null default '',
  notes               text not null default '',
  national_id         text not null default '',
  allergies           text not null default '',
  chronic_diseases    text not null default '',
  physiological_status text not null default '',
  medical_notes       text not null default '',
  created_at          text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at          text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.appointments (
  id         bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  date       text not null default '',
  time       text not null default '',
  reason     text not null default '',
  notes      text not null default '',
  status     text not null default 'scheduled',
  created_at text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.catalog (
  id          bigint generated by default as identity primary key,
  name        text not null,
  price       bigint not null default 0,
  description text not null default '',
  price_usd   double precision not null default 0,
  cost_usd    double precision not null default 0,
  created_at  text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.materials (
  id         bigint generated by default as identity primary key,
  name       text not null,
  category   text not null default '',
  unit       text not null default '',
  quantity   double precision not null default 0,
  min_qty    double precision not null default 0,
  cost       bigint not null default 0,
  cost_usd   double precision not null default 0,
  supplier   text not null default '',
  notes      text not null default '',
  created_at text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.catalog_materials (
  id         bigint generated by default as identity primary key,
  catalog_id bigint not null references public.catalog(id) on delete cascade,
  material_id bigint not null references public.materials(id),
  qty        double precision not null default 1
);

create table if not exists public.invoices (
  id         bigint generated by default as identity primary key,
  invoice_no text not null unique,
  patient_id bigint not null references public.patients(id),
  date       text not null default '',
  usd_rate   double precision not null default 0,
  subtotal   bigint not null default 0,
  discount   bigint not null default 0,
  total      bigint not null default 0,
  paid       bigint not null default 0,
  subtotal_usd double precision not null default 0,
  discount_usd double precision not null default 0,
  total_usd  double precision not null default 0,
  paid_usd   double precision not null default 0,
  status     text not null default 'unpaid',
  notes      text not null default '',
  created_by text not null default '',
  created_at text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.invoice_items (
  id         bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  name       text not null default '',
  cost       bigint not null default 0,
  qty        bigint not null default 1,
  cost_usd   double precision not null default 0,
  catalog_id bigint
);

create table if not exists public.invoice_materials (
  id          bigint generated by default as identity primary key,
  invoice_id  bigint not null references public.invoices(id) on delete cascade,
  item_id     bigint not null default 0,
  material_id bigint not null references public.materials(id),
  qty         double precision not null default 0
);

create table if not exists public.stock_movements (
  id         bigint generated by default as identity primary key,
  material_id bigint not null references public.materials(id) on delete cascade,
  qty        double precision not null default 0,
  operation  text not null default '',
  reference  text not null default '',
  user_name  text not null default '',
  note       text not null default '',
  created_at text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.expenses (
  id         bigint generated by default as identity primary key,
  category   text not null default '',
  amount     bigint not null default 0,
  amount_usd double precision not null default 0,
  is_recurring integer not null default 0,
  recurrence text not null default 'monthly',
  next_due   text not null default '',
  last_generated text not null default '',
  note       text not null default '',
  date       text not null default '',
  created_by text not null default '',
  created_at text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.settings (
  key   text primary key,
  value text not null default ''
);

create table if not exists public.patient_files (
  id          bigint generated by default as identity primary key,
  patient_id  bigint not null references public.patients(id) on delete cascade,
  filename    text not null default '',
  stored_name text not null default '',
  ftype       text not null default 'other',
  mime        text not null default '',
  size        bigint not null default 0,
  created_at  text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.patient_medications (
  id                  bigint generated by default as identity primary key,
  patient_id          bigint not null references public.patients(id) on delete cascade,
  scientific_name     text not null default '',
  trade_name          text not null default '',
  dose                text not null default '',
  form                text not null default '',
  route               text not null default '',
  frequency           text not null default '',
  start_date          text not null default '',
  end_date            text not null default '',
  category            text not null default 'prescription',
  prescriber          text not null default '',
  prescriber_specialty text not null default '',
  pharmacist          text not null default '',
  dispense_date       text not null default '',
  dispense_place      text not null default '',
  next_review         text not null default '',
  notes               text not null default '',
  active              integer not null default 1,
  created_at          text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.medicines (
  id              bigint generated by default as identity primary key,
  trade_name      text not null default '',
  scientific_name text not null default '',
  dose            text not null default '',
  form            text not null default '',
  route           text not null default '',
  frequency       text not null default '',
  category        text not null default 'prescription',
  created_at      text not null default to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- ---------------------------------------------------------------------
--  1.b) أعمدة إضافية للترقية (في حال وجود الجداول من نسخة سابقة)
-- ---------------------------------------------------------------------
alter table public.users     add column if not exists permissions      text not null default '';
alter table public.catalog   add column if not exists price_usd        double precision not null default 0;
alter table public.catalog   add column if not exists cost_usd         double precision not null default 0;
alter table public.materials add column if not exists cost_usd         double precision not null default 0;
alter table public.invoices  add column if not exists subtotal_usd     double precision not null default 0;
alter table public.invoices  add column if not exists discount_usd     double precision not null default 0;
alter table public.invoices  add column if not exists total_usd        double precision not null default 0;
alter table public.invoices  add column if not exists paid_usd         double precision not null default 0;
alter table public.invoice_items add column if not exists cost_usd     double precision not null default 0;
alter table public.expenses  add column if not exists amount_usd       double precision not null default 0;
alter table public.expenses  add column if not exists is_recurring     integer not null default 0;
alter table public.expenses  add column if not exists recurrence       text not null default 'monthly';
alter table public.expenses  add column if not exists next_due         text not null default '';
alter table public.expenses  add column if not exists last_generated   text not null default '';

-- ---------------------------------------------------------------------
--  2) فهارس مساعدة للبحث السريع من الجوال
-- ---------------------------------------------------------------------
create index if not exists idx_patients_name      on public.patients (name);
create index if not exists idx_patients_phone      on public.patients (phone);
create index if not exists idx_appointments_date   on public.appointments (date);
create index if not exists idx_invoices_patient    on public.invoices (patient_id);
create index if not exists idx_meds_patient        on public.patient_medications (patient_id);

-- ---------------------------------------------------------------------
--  3) الأمان (RLS): المستخدمون المسجّلون عبر Supabase Auth يصلون لكل البيانات.
--     تطبيق السطح المكتب يستخدم المفتاح السري (service_role) ويتجاوز RLS.
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'users','patients','appointments','catalog','materials','catalog_materials',
    'invoices','invoice_items','invoice_materials','stock_movements','expenses',
    'settings','patient_files','patient_medications','medicines'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "authenticated_all" on public.%I', t);
    execute format(
      'create policy "authenticated_all" on public.%I for all to authenticated using (true) with check (true)',
      t
    );
  end loop;
end $$;

-- ---------------------------------------------------------------------
--  4) دالة مزامنة التسلسلات: تُستدعى بعد رفع نسخة كاملة من السطح المكتب
--     حتى تبدأ المعرّفات الجديدة (المضافة من الجوال) بعد أكبر id موجود.
-- ---------------------------------------------------------------------
create or replace function public.reset_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  t text;
  seq text;
  mx bigint;
begin
  foreach t in array array[
    'users','patients','appointments','catalog','materials','catalog_materials',
    'invoices','invoice_items','invoice_materials','stock_movements','expenses',
    'patient_files','patient_medications','medicines'
  ]
  loop
    seq := pg_get_serial_sequence('public.' || quote_ident(t), 'id');
    if seq is not null then
      execute format('select coalesce(max(id), 0) from public.%I', t) into mx;
      if mx > 0 then
        perform setval(seq, mx, true);
      end if;
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------------
--  تم. الخطوة التالية: أنشئ مستخدماً من  Authentication > Users > Add user
--  (البريد + كلمة المرور) ليستخدمه تطبيق الأندرويد لتسجيل الدخول.
-- ---------------------------------------------------------------------